# Generated by Django 2.0.2 on 2019-12-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cHolder',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='order',
            name='cardNo',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='order',
            name='cvv',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='expDate',
            field=models.CharField(default='', max_length=12),
        ),
    ]
