# Generated by Django 2.0.2 on 2019-12-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20191230_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.CharField(default='', max_length=50),
        ),
    ]
