# Generated by Django 2.0.2 on 2020-01-01 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
